# Generated by Django 3.2.19 on 2023-07-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
