# Generated by Django 4.2 on 2023-04-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('score', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
