# Generated by Django 4.2 on 2023-04-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_langue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
